### ISSUE TITLE
InvalidPackage: Package not included in Android

### ISSUE THREAD

**Issue by laviua** [drusin/LibgdxLombokTest#1]
> InvalidPackage: Package not included in Android
> 
> C:\Users\users.gradle\caches\modules-2\files-2.1\org.projectlombok\lombok\1.16.6\9d3a47307466b28632bf35f8972ae9d703879416\lombok-1.16.6.jar: Invalid package reference in library; not included in Android: java.lang.instrument. Referenced from lombok.launch.Agent.
> Priority: 6 / 10
> Category: Correctness
> Severity: Error
> Explanation: Package not included in Android.
> This check scans through libraries looking for calls to APIs that are not included in Android.

**Comment by drusin** [comment]
If your build fails because of this lint error, you can disable aborting build on found lint errors like it's described [here](http://stackoverflow.com/questions/20699147/gradle-build-fails-on-lint-task).
The actual "problem" is within the lombok library itself, as it is primarily targeted for "normal" java usage, not Android.
There is [another project](https://github.com/evant/android-retrolambda-lombok) with the aim to provide lombok and retrolambda to android without causing lint errors, but it does not look very up-to-date.
I did not have any actual runtime problems with lombok on the Android build of my libGDX projects yet, so disabling the build abortion for this problem seems like an ok workaround for me.
